markdown: kramdown
kramdown:
  #input: GFM
  title: "Test Title for Config Check"
  #theme: jekyll-theme-cayman
  #theme: minima
  #highlighter: rouge
  #parse_block_html: true
  #parse_span_html: true
  #hard_wrap: false
  #parse_block_html: true
  #html_to_native: false
